#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 input_file output_file"
  exit 1
fi

input_file="$1"
output_file="$2"

if [ ! -f "$input_file" ]; then
  echo "Input file not found: $input_file"
  exit 1
fi

ffmpeg -i "$input_file" -vf "scale=3840:2160:flags=neighbor" -r 60 -rc constqp -qp 19 -c:a copy "$output_file"

