#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <input_video> <subtitle_file> <output_name>"
    exit 1
fi

# Assign input arguments to variables
input_video="$1"
subtitle_file="$2"
output_name="$3"

# Check if input video file exists
if [ ! -f "$input_video" ]; then
    echo "Input video file not found: $input_video"
    exit 1
fi

# Check if subtitle file exists
if [ ! -f "$subtitle_file" ]; then
    echo "Subtitle file not found: $subtitle_file"
    exit 1
fi

# Set the font path
font_path="./fonts/Montserrat-x-bold.ttf"

# Run ffmpeg command
ffmpeg -i "$input_video" -vf "subtitles=$subtitle_file:force_style='Font=$font_path,Fontsize=14,Alignment=2,BorderStyle=0,Bold=1,Outline=0,Karaoke=1'" -c:a copy -c:v libx264 -crf 23 -preset veryfast "${output_name}.mp4"

# Check if ffmpeg command was successful
if [ $? -eq 0 ]; then
    echo "Conversion completed successfully. Output file: ${output_name}.mp4"
else
    echo "Error during conversion."
fi

