#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input_directory>"
    exit 1
fi

input_folder="$1"
ext="$2"
output_filename="output_$(uuidgen).mp4"

for f in "$input_folder"/*.$ext; do echo "file '$PWD/$f'"; done

ffmpeg -f concat -safe 0 -i <(for f in "$input_folder"/*.$ext; do echo "file '$PWD/$f'"; done) -c copy "$output_filename"

