#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 input_file.mp4 output_file.mp4"
  exit 1
fi

input_file="$1"
output_file="$2"

# Run FFmpeg command
ffmpeg -i "$input_file" -filter_complex "drawtext=text='Utopia':fontfile=dash/dash.otf:fontsize=50:x=15:y=15:fontcolor=white" -c:a copy "$output_file"

