#!/bin/bash


if [ $# -ne 2 ]
  then
    echo "Please provide two arguments for the Python script"
    exit 1
fi

arg1=$1
arg2=$2

# Loop 5 times
for i in {1..5}
do
    python3 edit.py "$arg1" "$arg2"
done

wait
