#!/bin/bash


if [ $# -ne 4 ]
  then
    echo "Please provide four arguments for the Python script"
    exit 1
fi

arg1=$1
arg2=$2
arg3=$3
arg4=$4

# Loop 5 times
for i in {1..5}
do
    python3 edit.py "$arg1" "$arg2" "$arg3" "$arg4"
done

wait
