#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 input_video input_audio "
  exit 1
fi

input_video="$1"
input_audio="$2"

# Generate a unique filename with the specified extension
output_filename=${input_video}_$(uuidgen).mp4

# Run the ffmpeg command with the provided inputs and output filename
ffmpeg -i "$input_video" -i "$input_audio" -map 0:v -map 1:a -c:v copy -c:a copy -shortest "$output_filename"

echo "Output video saved as: $output_filename"

