#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <input_file> <output_file>"
  exit 1
fi

input_file="$1"
output_file="$2"

ffmpeg -i "$input_file" -filter_complex "drawtext=text='Utopia':fontfile='./fonts/Aquire-BW0ox.otf':fontsize=35:x=40:y=40:fontcolor=white" -c:a copy "$output_file"

